on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This step checks out your repository code

      - name: Cross-compiler install
        run: sudo apt install --yes {gcc,binutils}-arm-linux-gnueabihf

      - name: Compiling for pynq
        run: arm-linux-gnueabihf-gcc -o out.exe main.c

      - name: Output file
        run: sudo file out.exe

      - name: Compile C program
        run: gcc main.c -o main.exe
        
      - name: Upload pynq artifact
        uses: actions/upload-artifact@v2
        with:
          name: out-exe-artifact
          path: out.exe
